# Generated by Django 4.1.7 on 2023-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=20)),
                ('Brand_Email', models.EmailField(max_length=254, null=True)),
                ('Brand_Password', models.CharField(max_length=20, null=True)),
                ('Brand_Address', models.TextField(null=True)),
                ('Brand_City', models.CharField(max_length=25, null=True)),
                ('Brand_State', models.CharField(max_length=20, null=True)),
                ('Brand_Zip', models.CharField(max_length=15, null=True)),
                ('Brands_Logo', models.ImageField(null=True, upload_to='Brands_Logo/')),
            ],
        ),
    ]
