# Generated by Django 4.1.7 on 2023-04-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
